### ISSUE TITLE
#추가 기능 구현

### ISSUE THREAD

**Issue by do-eun** [gomin-solution/Frontend#19]
댓글로 달아주시면 제가 확인하고 추가하겠습니다!

**완료된 구현 사항** 
- [x] 설정 창에서 공지사항, 이메일 문의, 신고접수 등의 기능 적용
- [x] 웹에서 스윗알러트 사이즈 줄이기
- [x] 인풋 누르면 달력 뜨도록 하기(모바일에서는 클릭시 바로 달력 나오는거 확인!)
- [x] 사진 미리보기 사이즈 웹화면 사이즈에 맞춰주기
- [x] 답해주기 글 작성 후 상세페이지 이동 매끄럽게 만들기(해결 : 코드 중복으로 인한 버벅임이였음!)
- [x] 리액트 모먼트 아닌 다른 라이브러리 사용하기
- [x] 투표 게시글 작성 후 업데이트 오류
- [x] 정렬 필터 기능
- [x] 사파리 dayJs 오류
- [x] 리워드 얻을시 애니메이션 적용하기
- [x] 조언하기 게시글 채택기능
- [x] alert 커스텀
- [x] Optimistic Update 좋아요, 북마크 업데이트, 투표 업데이트
- [x] 대댓글 작성하기
- [x] 게시글, 게시글 댓글 신고하기 기능
- [x] 골라주기 마감 후 결과 조회 가능하도록 변경
- [x] 프로필 사진 빼고 등급제로 바꿔놓기
- [x] 소셜 로그인 카카오
- [x] 스크롤 최상단으로 올리기
- [x] 게시글 상세페이지 이동 후 되돌아가면 스크롤 기억하기
- [x] 사파리 화면에서 footer 잘리는 오류, input 창에 클릭시 확대되는 오류
- [x] 아이디 중복확인 검사 후 재입력하면 검사 다시 할 수 있도록 수정하기

**Comment by Jeongpyo-Hong** [comment]
설정 창에서 공지사항, 이메일 문의, 신고접수 등의 기능 적용

**Comment by do-eun** [comment]
리액트 모먼트 대신 다른 라이브러리 사용하기
https://github.com/you-dont-need/You-Dont-Need-Momentjs

**Comment by do-eun** [comment]
사파리 모바일에서 하단 잘림 오류
인풋창 클릭시 확대되는 오류
설정된 폰트 색이 없을시 버튼같은 경우 파란색으로 나오는 오류 있음
푸터 부분도 웹에서는 안잘리는데 모바일로 켰을시 글자가 잘리는 오류있음


크롬 모바일 앱도 확인하기!!
