### ISSUE TITLE
유저 피드백 정리

### ISSUE THREAD

**Issue by do-eun** [gomin-solution/Frontend#198]
- [x] 1. 토큰이 만료되면 status code 405 에러가 뜨고 catch해서 interceptor를 함. 오류코드기 때문에 콘솔창에 찍힘
- [x] 2. 답해주기에서 게시글을 클릭할 때 불러오는 과정에서 빈 화면이 뜸. 순간적으로 보이는 상황에서 디폴트 텍스트가 있으면 함.
- [x] 3. 행운편지 막누르다보면 undefined 뜸. 토큰이 만료된 타이밍에 행운 편지 클릭시 해당 데이터가 없어 undefined를 반환
- [x] 4. 닉네임 중복체크 하는 부분에서 글자를 무한대로 적을 수 있고 글자가 중복체크 버튼에 가려짐
- [x] 5. 첫 로그인 후 닉네임 중복 확인 후 닉네임을 변경 하려고 했더니 변경이 안됨
- [x] 6. 모바일 사파리에서 회원가입시 중복확인 버튼을 누리고 그 다음에 확인을 눌렀을 때 반응이 한참 없다가 알럿이 없어짐 중복확인이 완료되면 완료되었다고 표시되는것도 좋을것 같아요. 버튼을 disable하거나요 (카카오 로그인)
- [ ] 7. 어느 곳에서든 javascript: alert(document.cookies); 를 하면 쿠키 확인가능.
- [ ] 8. devtool을 보니 express를 사용했다고 x-powered-by 로 확인이 가능합니다. 가능하면 helmet을 씌워주셨으면 함.
- [ ] 9. 전반적으로 로딩 시간이 길다.
- [x] 10. 사진이 엑박이 떴다가 돌아오는 경우가 있음.
- [x] 11. 가입 할 때 닉네임 두번째로 적으면 사용 가능여부에 대해 확인할 수 없는 것 같다.
- [x] 12. 골라주기 마감시간의 표시를 조금 더 부드럽게 해주면 좋겠다 
- [x] 13. 마감시간 기본값이 현재시간이 아닌 1시간 이후로 되있으면 좋을거 같다.
- [ ] 14. 답변해주기 input창 구분이 잘 되도록 가독성 높이기 (DE)
- [x] 15. 로그인을 유도하기 위해서 모달창이 뜨는데 누르면 바로 로그인 페이지로 가도록 변경됐으면 함.
- [ ] 16. 처음에 앱 설명할 때 skip버튼 추가. (DE)
- [ ] 17.  인트로의 화살표를 좀 더 명확하게 표시했으면 함. (DE)
- [x] 18. 댓글이 최신순 정렬이 아니고 등록순 누르고 다시 버튼누르면 최신순이 없어진다.
- [x] 19. 북마크한 글은 삭제 되지 않음
- [x] 20. 카카오로 가입 시 닉네임 설정창을 벗어나면 닉네임이 null로 가입되는 오류
- [ ] 21. 사진 선택 삭제 기능(지금은 덮어쓰기로 적용되어 있음)
- [ ] 22. 수정시 사진 남아있도록 변경하기. 지금은 수정을 누르면 사진을 다시 업로드 해야함.
- [x] 23. 고민접기 -> 검색 -> 추천게시글 들어감 -> 뒤로가기버튼 로직에 문제가 있음.
- [x] 24. 개인정보 변경할 때 닉네임 중복확인 추가
- [x] 25. 내가 작성한 고민글 페이지에서도 글을 바로 작성할 수 있도록 하기
- [x] 26. 메인 화면에서 추천글 클릭할 수 있는 건지 알 수 있게 하기
- [ ] 27. 쪽지 방 없을 때 쪽지함이 비어 있는 이미지를 활용해서 여백을 좀 채워주기 (DE)
- [x] 28. 추천글 들어간 후 뒤로가기 클릭 시 메인으로 돌아가게 해주기
- [ ] 29. 고민 삭제할때 한번 더 확인할수있는 창이 뜨기
- [x] 30. 댓글 필터에 최신순 댓글 정렬도 추가하기
- [ ] 31. 빈 내용이면 쪽지가 아예 안 가도록 수정하기.
- [ ] 32. 비밀번호 찾기, 아이디 찾기 기능.
- [ ] 33.  고민접기 부분에 상단 카테고리 골라주기,답해주기 부분도 고정
- [ ] 34. 인트로 넘어가는 화살표 부분이 너무 작음. 아니면 다른 곳을 클릭해도 넘어가도록 수정.
- [ ] 35. 인트로 뒤로가기 버튼
- [ ] 36. 인트로 마지막 페이지에 스킵버튼, 이동버튼 삭제
- [ ] 37. 내가 작성한 고민, 북마크한 고민에 커서 적용
- [ ] 38. 회원가입이 완료시 로그인 후 메인으로 바로 이동 (회원가입시 setCookie)
- [ ] 39. 로그인 페이지에 이미지 로딩이 느림
- [ ] 40. 답글 작성을 하단으로 이동시킨 후 답글 클릭시 페이지 뷰 이동.
- [ ]

**Comment by Jeongpyo-Hong** [comment]
1.
error를 빈 객체로 변환하여 콘솔창에서 보이지 않도록 할 수 있음
console.warn = console.error = () => {};
// or IIFE
(() => { console.warn = console.error = () => {}} )();

**Comment by Jeongpyo-Hong** [comment]
**15. 로그인창 바로 가는 기능 추가**
취소 / 로그인하러 가기

**Comment by Jeongpyo-Hong** [comment]
**18. 화살표 버튼 가독성**
bullet 추가

**Comment by Jeongpyo-Hong** [comment]
**18. 화살표 버튼 가독성**
bullet 추가

**Comment by do-eun** [comment]
**15. 로그인 유도 alert에서 바로 이동하도록 수정**
확인시 로그인 페이지로 이동하도록 변경

**Comment by do-eun** [comment]
**12. 마감시간 검사를 input 속성 검사에서 alert로 수정 (통일)**
input 속성으로 마감시간의 유효성 검사를 걸었더니 브라우저마다 오류 메세지가 다르게 적용 됨. 
기존의 속성을 지우고 마감시간 검사를 alert로 통일

**Comment by Jeongpyo-Hong** [comment]
**5. 첫 로그인 후 닉네임 중복 확인 후 닉네임을 변경 하려고 했더니 변경이 안됨**
중복검사 후 alert를 취소, 사용 두 가지로 변경

**Comment by do-eun** [comment]
**2. 게시글 클릭시 빈화면이 뜸 -> isLoading을 설정하여 로딩바를 추가**
유저가 게시글 조회시 빈화면이 아닌 로딩이 뜨도록 변경

**Comment by do-eun** [comment]
**20. 북마크한 글 삭제 안되는 오류**
백에서 수정 완료.

**Comment by Jeongpyo-Hong** [comment]
**10. 사진이 엑박이 떴다가 돌아오는 경우가 있음.**
setting페이지 관련 오류이며, default로 빈 값을 넣어주었음

**Comment by Jeongpyo-Hong** [comment]
**21. 카카오로 가입시 닉네임 설정창을 벗어나면 닉네임이 null로 가입되는 오류**
닉네임을 입력하지 않고 비정상적으로 접근 시, token과 userKey를 할당하지 않도록 하고, 비로그인한 유저로 처리

**Comment by Jeongpyo-Hong** [comment]
**24. 개인정보 변경할 때 닉네임 중복확인 추가**
중복된 닉네임인 경우 alert 예외처리 해줌

**Comment by Jeongpyo-Hong** [comment]
**25. 내가 작성한 고민글 페이지에서도 글을 바로 작성할 수 있도록 하기**
내가 작성한 고민글에서 dial 추가

**Comment by Jeongpyo-Hong** [comment]
**26. 메인 화면에서 추천글 클릭할 수 있는 건지 알 수 있게 하기**
cursor: pointer 적용

**Comment by do-eun** [comment]
**28. 추천글 들어간 후 뒤로가기 클릭 시 메인으로 돌아가게 해주기**

추천글에서 상세페이지 이동시 useLocation으로 state 값을 넘겨줌

**Comment by do-eun** [comment]
**30. 댓글 필터에 최신순 댓글 정렬도 추가하기**
등록순, 좋아요순, 최신순으로 정렬가능
