### ISSUE TITLE
유저 피드백 개선

### ISSUE THREAD

**Issue by do-eun** [gomin-solution/Frontend#199]
- [x]  1. 토큰이 만료되면 status code 405 에러가 뜨고 catch해서 interceptor를 함. 오류코드기 때문에 콘솔창에 찍힘
- [x]  2. 답해주기에서 게시글을 클릭할 때 불러오는 과정에서 빈 화면이 뜸. 순간적으로 보이는 상황에서 디폴트 텍스트가 있으면 함.
- [x]  3. 행운편지 막누르다보면 undefined 뜸. 토큰이 만료된 타이밍에 행운 편지 클릭시 해당 데이터가 없어 undefined를 반환
- [x]  4. 닉네임 중복체크 하는 부분에서 글자를 무한대로 적을 수 있고 글자가 중복체크 버튼에 가려짐
- [x]  5. 첫 로그인 후 닉네임 중복 확인 후 닉네임을 변경 하려고 했더니 변경이 안됨
- [x]  6. 모바일 사파리에서 회원가입시 중복확인 버튼을 누리고 그 다음에 확인을 눌렀을 때 반응이 한참 없다가 알럿이 없어짐 중복확인이 완료되면 완료되었다고 표시되는것도 좋을것 같아요. 버튼을 disable하거나요 (카카오 로그인)
- [x]  ~~7. 어느 곳에서든 javascript: alert(document.cookies); 를 하면 쿠키 확인가능.~~
- [x]  ~~8. devtool을 보니 express를 사용했다고 x-powered-by 로 확인이 가능합니다. 가능하면 helmet을 씌워주셨으면 함.~~
- [ ]  9. 전반적으로 로딩 시간이 길다.
- [x]  10. 사진이 엑박이 떴다가 돌아오는 경우가 있음.
- [x]  11. 가입 할 때 닉네임 두번째로 적으면 사용 가능여부에 대해 확인할 수 없는 것 같다.
- [x]  12. 골라주기 마감시간의 표시를 조금 더 부드럽게 해주면 좋겠다
- [x]  13. 마감시간 기본값이 현재시간이 아닌 1시간 이후로 되있으면 좋을거 같다.
- [x]  ~~14. 답변해주기 input창 구분이 잘 되도록 가독성 높이기 (DE)~~
- [x]  15. 로그인을 유도하기 위해서 모달창이 뜨는데 누르면 바로 로그인 페이지로 가도록 변경됐으면 함.
- [x]  16. 처음에 앱 설명할 때 skip버튼 추가. (DE)
- [x]  17. 인트로의 화살표를 좀 더 명확하게 표시했으면 함. (DE)
- [x]  18. 댓글이 최신순 정렬이 아니고 등록순 누르고 다시 버튼누르면 최신순이 없어진다.
- [x]  19. 북마크한 글은 삭제 되지 않음
- [x]  20. 카카오로 가입 시 닉네임 설정창을 벗어나면 닉네임이 null로 가입되는 오류
- [ ]  21. 사진 선택 삭제 기능(지금은 덮어쓰기로 적용되어 있음)
- [ ]  22. 수정시 사진 남아있도록 변경하기. 지금은 수정을 누르면 사진을 다시 업로드 해야함.
- [x]  23. 고민접기 -> 검색 -> 추천게시글 들어감 -> 뒤로가기버튼 로직에 문제가 있음.
- [x]  24. 개인정보 변경할 때 닉네임 중복확인 추가
- [x]  25. 내가 작성한 고민글 페이지에서도 글을 바로 작성할 수 있도록 하기
- [x]  26. 메인 화면에서 추천글 클릭할 수 있는 건지 알 수 있게 하기
- [x]  27. 쪽지 방 없을 때 쪽지함이 비어 있는 이미지를 활용해서 여백을 좀 채워주기 (DE)
- [x]  28. 추천글 들어간 후 뒤로가기 클릭 시 메인으로 돌아가게 해주기
- [x]  29. 고민 삭제할때 한번 더 확인할수있는 창이 뜨기
- [x]  30. 댓글 필터에 최신순 댓글 정렬도 추가하기
- [x]  31. 빈 내용이면 쪽지가 아예 안 가도록 수정하기.
- [x]   32. 비밀번호 찾기, 아이디 찾기 기능 빼고 대체하기 => 아직 고민접기에 가입하지 않으셨나요? 
- [x]  33. 고민접기 부분에 상단 카테고리 골라주기,답해주기 부분도 고정
- [ ]  ~~34. 인트로 넘어가는 부분이 다른 곳을 클릭해도 넘어가도록 수정.~~
- [ ]  ~~35. 인트로 뒤로가기 버튼~~
- [x]  36. 인트로 마지막 페이지에 스킵버튼, 이동버튼 삭제
- [x]  37. 내가 작성한 고민, 북마크한 고민에 커서 적용
- [x]  38. 회원가입이 완료시 로그인 후 메인으로 바로 이동 (회원가입시 setCookie)
- [ ]  39. 로그인 페이지에 이미지 로딩이 느림
- [x]  40. 답글 작성을 하단으로 이동시킨 후 답글 클릭시 페이지 뷰 이동.
- [x] 41. 쪽지 input 창 fixed로 변경하기
- [x] 42. 이미지 수정 오류
- [x] 43. 회원가입창에서 비밀번호에 쓸 수 있는 특수문자를 표기
- [x] 44.confirm password에서 다르게 입력을 하면 밑에 일치하지 않다고 바로바로 표기 하기
- [x] ~~45. 글 작성 버튼이 hover가 아닌 클릭시 옵션이 뜨도록 변경~~
- [ ] 46.  투표시 수정 가능하도록
- [x] 47. 닉네임 변경시 변경하기를 눌러서 닉네임을 입력하고 변경을 누르는 로직
- [x] 48. 소셜로그인 유저에게도 비밀번호 변경이 안 뜨도록 바꾸기
- [ ] 49. location 대신 navigation을 쓰기 (location의 경우 리액트가 재실행 됨)
- [ ] 50. 이용방법 부분을 예쁘게 수정하기
- [x] 51. 해결한 고민수에 대한 설명 해주기 => 이용방법에 추가하기
- [x] 52. 신고접수 후 신고완료 됐습니다. 쪽지 보내고 쪽지 완료 됐습니다. 등 띄워주기 => 스낵바
- [x] 53. 글 작성, 글삭제, 글 수정 -> 스낵바 띄워주기
- [x] 54. 검색버튼 미동작
- [ ] 55. 북마크 하나를 누르면 페이지를 다 호출하는 방식 개선하기
- [x] 56. ‘답해주기’ 이용시 작성중인 답변인 한문장이 넘어가면 수정하기 어렵다. 
- [ ] 57. 사파리 브라우저 이용 중 장시간 켜 놓은 경우 로그인이 풀려 새로고침을 해도 ‘잠시후 다시 시도해주세요’라는 문구가 떴습니다
- [ ] 58. 삼성 인터넷 이용하면 제일 처음페이지에서 바로 안 들어가지고 오류 난 다음에 뜬다.

**Comment by do-eun** [comment]
**1. 오류 콘솔 없애기**
error를 빈 객체로 변환하여 콘솔창에서 보이지 않도록 할 수 있음
console.warn = console.error = () => {};
// or IIFE
(() => { console.warn = console.error = () => {}} )();

**Comment by do-eun** [comment]
**15. 로그인창 바로 가는 기능 추가**
취소 / 로그인하러 가기

**Comment by do-eun** [comment]
**17. Intro skip**
skip 버튼 추가하고 클릭 시 마지막 swiper로 이동

**Comment by do-eun** [comment]
**18. 화살표 버튼 가독성**
bullet 추가

**Comment by do-eun** [comment]
**19. 댓글은 등록순, 좋아요만 있는게 맞음. 코드 오류**
const [menu, setMenu] = useState("최신순") 에서
const [menu, setMenu] = useState(filters[0].filter); 로 초기값 수정

**Comment by do-eun** [comment]
**15. 로그인 유도 alert에서 바로 이동하도록 수정**
확인시 로그인 페이지로 이동하도록 변경

**Comment by do-eun** [comment]
**3. 행운편지 막누르다보면 undefined 뜸. 토큰이 만료된 타이밍에 행운 편지 클릭시 해당 데이터가 없어 undefined를 반환**
페이지 로딩화면을 추가하여 로딩중 클릭하지 못하도록 하여 해결 + error 생길 때 error alert 보여주기

**Comment by do-eun** [comment]
**12. 마감시간 검사를 input 속성 검사에서 alert로 수정 (통일)**
input 속성으로 마감시간의 유효성 검사를 걸었더니 브라우저마다 오류 메세지가 다르게 적용 됨.
기존의 속성을 지우고 마감시간 검사를 alert로 통일

**Comment by do-eun** [comment]
**5. 첫 로그인 후 닉네임 중복 확인 후 닉네임을 변경 하려고 했더니 변경이 안됨**
11. 가입 할 때 닉네임 두번째로 적으면 사용 가능여부에 대해 확인할 수 없는 것 같다.
중복검사 후 alert를 취소, 사용 두 가지로 변경

**Comment by do-eun** [comment]
**2. 게시글 클릭시 빈화면이 뜸 -> isLoading을 설정하여 로딩바를 추가**
유저가 게시글 조회시 빈화면이 아닌 로딩이 뜨도록 변경

**Comment by do-eun** [comment]
**20. 북마크한 글 삭제 안되는 오류**
백에서 수정 완료.

**Comment by do-eun** [comment]
**10. 사진이 엑박이 떴다가 돌아오는 경우가 있음.**
setting페이지 관련 오류이며, default로 빈 값을 넣어주었음

**Comment by do-eun** [comment]
**21. 카카오로 가입시 닉네임 설정창을 벗어나면 닉네임이 null로 가입되는 오류**
닉네임을 입력하지 않고 비정상적으로 접근 시, token과 userKey를 할당하지 않도록 하고, 비로그인한 유저로 처리

**Comment by do-eun** [comment]
**24. 개인정보 변경할 때 닉네임 중복확인 추가**
중복된 닉네임인 경우 alert 예외처리 해줌

**Comment by do-eun** [comment]
**25. 내가 작성한 고민글 페이지에서도 글을 바로 작성할 수 있도록 하기**
내가 작성한 고민글에서 dial 추가

**Comment by do-eun** [comment]
**26. 메인 화면에서 추천글 클릭할 수 있는 건지 알 수 있게 하기**
cursor: pointer 적용

**Comment by do-eun** [comment]
**23. 검색창에서 게시글 상세페이지 조회 후 뒤로가기 누르면 검색-> 상세 -> 검색 -> 상세 반복**
'''javascript'''
const navi = sessionStorage.getItem("searchNav"); //세션에 페이지 라우터를 저장하여 
// 검색바 이전 페이지로 이동시킴. board-advice or board-choice 

{navi === null ? (
          <StBackcon
            onClick={() => {
              nav(-1);
            }}
          />
        ) : (
          <StBackcon
            onClick={() => {
              nav(navi);
            }}
          />
        )}

// 비정상적인 접근으로 올 경우 -1로 이전 페이지로 보내줌
```

**Comment by do-eun** [comment]
**28. 추천글 들어간 후 뒤로가기 클릭 시 메인으로 돌아가게 해주기**

추천글에서 상세페이지 이동시 useLocation으로 state 값을 넘겨줌

**Comment by do-eun** [comment]
**28. 추천글 들어간 후 뒤로가기 클릭 시 메인으로 돌아가게 해주기**

추천글에서 상세페이지 이동시 useLocation으로 state 값을 넘겨줌

**Comment by do-eun** [comment]
**37. 내가 작성한 고민, 북마크한 고민에 커서 적용**
cursor : pointer  적용

**Comment by Jeongpyo-Hong** [comment]
**29. 고민 삭제할 때 한번 더 확인할 수 있는 창이 뜨기**
버튼 클릭 시 alert 추가

**Comment by do-eun** [comment]
**42. 이미지 수정 오류**
이미지 수정시 instance 변경. multipart 추가

**Comment by Jeongpyo-Hong** [comment]
**31. 빈 내용이면 쪽지가 아예 안 가도록 수정하기.**
placeholder에 내용 추가

**Comment by do-eun** [comment]
**43. 회원가입창에서 비밀번호에 쓸 수 있는 특수문자를 표기**
회원가입시 사용할 수 있는 특수문자(!@#$%^&*) 표기
개인정보 변경에도 특수문자 표기

**Comment by do-eun** [comment]
**33. 고민접기 부분에 상단 카테고리 골라주기,답해주기 부분도 고정**
fixed로 고정 후 필요한 값은 props로 전달

**Comment by Jeongpyo-Hong** [comment]
**38. 회원가입이 완료시 로그인 후 메인으로 바로 이동 (회원가입시 setCookie)**
회원가입 시 token, userKey 저장 후 메인페이지로 이동, 회원가입 시 환영 alert 닉네임으로 띄우도록 변경

**Comment by do-eun** [comment]
**48. 소셜로그인 유저에게도 비밀번호 변경이 안 뜨도록 바꾸기**
백에서 소셜로그인한 유저의 정보를 boolean 값으로 받아서 처리

**Comment by do-eun** [comment]
**47.  닉네임 변경시 변경하기를 눌러서 닉네임을 입력하고 변경을 누르는 로직**
알러트 창으로 닉네임 받는걸로 변경.

**Comment by do-eun** [comment]
**32. 비밀번호 찾기, 아이디 찾기 기능 빼고 대체하기 => 아직 고민접기에 가입하지 않으셨나요?**
없는 기능은 준비중이 아닌 빼는게 맞다고 판단. 회원가입 유도 멘트로 수정

**Comment by do-eun** [comment]
**54. 검색버튼 미동작**
fixed로 바꾸면서 z-index 미수정으로 발생한 오류. 헤더를 10으로 설정하고 버튼을 9로 설정

**Comment by do-eun** [comment]
**51. 해결한 고민수에 대한 설명 해주기 => 이용방법에 추가하기**

해결한 고민수 = 본인 투표 마감글 수 + 본인 게시글 채택한 수

**Comment by do-eun** [comment]
**44.confirm password에서 다르게 입력을 하면 밑에 일치하지 않다고 바로바로 표기 하기**

실시간으로 유효성 검사 적용 useForm에 mode: onChange 추가

**Comment by do-eun** [comment]
**45. 글 작성 버튼이 hover가 아닌 클릭시 옵션이 뜨도록 변경**
변경은 가능하나., hover 적용시 모바일에서 자동으로 닫히지 않고 버튼 클릭시에만 닫힘. 
원래 취지는 모바일 전용이기 때문에 그대로 가기로 결정..

**Comment by do-eun** [comment]
**53. 글 작성, 글삭제, 글 수정 -> 스낵바 띄워주기**
스낵바 대신 alert로 처리 
- 골라주기 조기 마감, 삭제 
- 답해주기 게시글, 댓글, 답글 삭제 

작성, 답해주기 수정은 페이지가 이동되기 때문에 따로 alert 처리 안함.

**Comment by do-eun** [comment]
**52. 신고접수 후 신고완료 됐습니다. 쪽지 보내고 쪽지 완료 됐습니다. 등 띄워주기 => 스낵바**

스낵바 대신 alert로 처리 => 쪽지를 보냈습니다/신고처리되었습니다. 
빈 내용일 경우 오류 메세지 띄우도록 수정 => 내용을 입력해주세요.

**Comment by do-eun** [comment]
**56. ‘답해주기’ 이용시 작성중인 답변인 한문장이 넘어가면 수정하기 어렵다.**
줄바꿈시 자동적으로 칸 늘어나도록 수정

**Comment by do-eun** [comment]
**40. 답글 작성을 하단으로 이동시킨 후 답글 클릭시 페이지 뷰 이동.**
페이지 뷰 이동은 빼고 답글 작성을 답글보다 하단으로 이동
