### ISSUE TITLE
보고 게시판 (코드 작성 전에 확인하기!)

### ISSUE THREAD

**Issue by do-eun** [gomin-solution/Frontend#60]
제가 해놓은 부분에서 수정이 필요한 부분은 어디인지 여기에 적도록 하겠습니다.
확인하신 후 수정하고 이모티콘으로 남겨주세요~

**Comment by do-eun** [comment]
- 헤더 좌측으로 수정 완료.
로그인 부분에 이전버튼 추가했습니다. 
회원가입 페이지도 헤더에 회원가입 타이틀 넣었습니다! 확인하시고 회원가입 부분 위쪽 여백 수정해주세요~

**Comment by Jeongpyo-Hong** [comment]
게시판 router는 board-choice 와 board-advice 로 나눌게요.
그리고 footer 고민접기 클릭 시 board-choice 로 이동하도록 바꿔둘게요!

**Comment by Jeongpyo-Hong** [comment]
마감시간 기능 적용 완료했고, 받아오는 데이터에서 endTime과 맞지 않아서 다시 맞춰보는 중입니다.

**Comment by do-eun** [comment]
사파리에서 데이 제이에스 오류 있음 !! NaN 으로 표기 됨..

**Comment by do-eun** [comment]
로그인 안 하고 접속시 get 요청 오류가 납니다!! 데일리 메세지를 클릭 안 해도 자동적으로 요청이 보내지네요..?!
그리고 추천글 부분도 같이 날라갑니다

**Comment by Jeongpyo-Hong** [comment]
infinite scroll에서 optimistic UI 적용하는 작업 할게요~
