### ISSUE TITLE
#31 [feat] 마감시간 기능 적용 (react-moment -> dayjs로 변경하여 적용)

### ISSUE THREAD

**Issue by Jeongpyo-Hong** [gomin-solution/Frontend#65]
일, 시간, 분 조건 구분하여 적용하였습니다.
리팩토링 할 수 있는 방법 찾으면 좋을 것 같아요.

**Comment by Jeongpyo-Hong** [comment]
dayjs로 구현하였으나, safari 환경에서 NaN으로 표시됩니다.
다른 라이브러리를 찾아야 할지, 아니면 보완 방법을 찾아야 할지 고민해봐야 할 것 같습니다.

**Comment by do-eun** [comment]
해결~~~

**Comment by do-eun** [comment]
문제 상황 : safari에서 DayJs 라이브러리 사용시 마감 날짜가 NaN으로 표기되는 오류

**1. 요구사항 :**
n일전, n시간 전, n분전으로 표기되도록 맞추기

**2. 선택지 :**
다른 라이브러리 사용하기
DayJs 오류 해결하기

**3. 의사결정 :**
구글링 결과 사파리는 날짜 포멧이 2020/11/11 형식만 사용이 가능. 

**4. 근거:**
백엔드에서 받아오는 날짜 데이터 형식을 
2020.01.01 -> 2020/01/01 으로 수정했더니 정상적으로 출력 됨.
